
spring:
  datasource:
    url: jdbc:postgresql://localhost:5488/db
    username: user
    password: password

  jpa:
    generate-ddl: true
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    statusTopic: "status-topic"

server:
  port: 8081