
spring:
  datasource:
    url: jdbc:postgresql://localhost:5488/db
    username: user
    password: password

  jpa:
    generate-ddl: true
    show-sql: true
  kafka:
    bootstrap-servers: "localhost:9092"
    statusTopic: "status-topic"
    consumer:
      group-id: "group-1"

server:
  port: 8081